### ISSUE TITLE
Find All References not working

### ISSUE THREAD

**Issue by njfm** [austin-----/code-gnu-global#1]
Not sure, but it seems this problem is due to the fact that at "referenceProvider.ts" the code portion "['--encode-path', "' '", '-rax', word]" should be:
['--encode-path', '" "', '-rax', word] (at the second parameter (encode-path), quotes should be like the ones used at "documentSymbolProvider.ts".
Thanks for this great extension,

**Comment by austin-----** [comment]
Thanks for digging this out. 0.1.2 publish with a fix.
