### ISSUE TITLE
[Bug] Unable to get auto complete to work (Win7)

### ISSUE THREAD

**Issue by csholmq** [austin-----/code-gnu-global#10]
I have installed this plugin on both my Win7 and OSX Yosemite and have not managed to get it working.

I've installed GNU Global 6.5.2 on both machines and added everything to path. Successfully run `gtags` in my project and I can see the three generated files. Not able to view them in the editor, but I assume that's because they're binary.

Have I missed something?

**Comment by austin-----** [comment]
After you have generated the three files, were you able to navigate to function definitions in VSCode?

**Comment by csholmq** [comment]
As in right click and *Go To Definition*? Not able to, no.

`global fun1` works, so it seems that `gtags`did it's job.

Pretty new to Visual Studio Code. Any console I can check for errors with the plugin?

**Comment by csholmq** [comment]
Sorry, my mistake. I accidentally ran `gtags` in my SW sub directory. But I opened my *complete* project in VSCode. So the global generated files weren't in root of the project.

Both *Go To Definition*,  *Peek Definition* and *Find All References* works fine now! Autocomplete doesn't work outside the current file though. Should it?

Get a lot of definition hits due to my build structure. I guess any configuration to exclude directories is done in gtags.conf?

**Comment by austin-----** [comment]
Gtags comes with its limitations, that is it does not do semantic analysis. Thus it does not understand class members and methods. So if you are trying to get autocompletion for class members, it only works for the current file based on textual info. On the other hand, autocompletion on the tags (class type, global functions, enums) that Gtags understands should work outside of the current file.

**Comment by csholmq** [comment]
I recorded an example where definitions already in the current file scope is matched successfully. But when I remove it, it nog longer works.

![autocomplete](https://cloud.githubusercontent.com/assets/1297882/12812825/9e64d1e4-cb34-11e5-9d57-9c2a84be51ca.gif)

**Comment by csholmq** [comment]
This is weird. Seems to be a bug where I don't get any autocompletion when I first start typing a symbol name. But when I move away from it (space or cursor) it immediately kicks in.

![autocomplete_bug](https://cloud.githubusercontent.com/assets/1297882/12814567/3c4309fc-cb40-11e5-9389-b0faff1a482f.gif)

**Comment by austin-----** [comment]
Does sounds like a bug. But I cannot reproduce it on my machine.

Could you please turn on "Help - Toggle Developer Tool" on see if you can find any error in the Javascript Console when autocompletion stopped working?

**Comment by csholmq** [comment]
It worked on OSX back home. But on work, on Win7, this showed up in the Console. Too many hits?

![image](https://cloud.githubusercontent.com/assets/1297882/12840217/bc8d55c6-cbe1-11e5-882b-b72195cdcc14.png)

**Comment by csholmq** [comment]
I can just add to this that `global -x ^A.*` doesn't seem to match properly on Win. Too many hits. Hence the need for such a big buffer. That and the size of the project of course.
