### ISSUE TITLE
Function name has no hyperlink as in the demo video

### ISSUE THREAD

**Issue by lianghu** [austin-----/code-gnu-global#11]
I installed the extention, it's great!

However,  there is no hyperlink associated to the function name as in the demo video.

In the video, just click on the function name (perform_code_completion) will jump to the defition.

How is that working?

**Comment by csholmq** [comment]
Press Ctrl and then hover. Works for both functions and definitions. If you then click on the hyperlink (while holding Ctrl) it jumps straight to the definition. Alt + Left to return.
