### ISSUE TITLE
CTRL Key behavior interferes with copy/paste

### ISSUE THREAD

**Issue by Arithmeticae** [austin-----/code-gnu-global#15]
I have a project that occasionally returns multiple lines for the "Go to Definition" feature. This works well, however the interaction between the CTRL key and functions with multiple definitions causes significant frustration when trying to use other CTRL based shortcuts like copy/paste on a function name with multiple definitions.

Example:
- Highlight a function declaration in a header (or wherever) that might be duplicated elsewhere, like an init function.
- With the cursor still over the function name press the CTRL key.
- The command palette will appear with the list of locations of possible definitions.

This will prevent you from copying the highlighted text as the cursor will now be located in the command palette window.

**Comment by csholmq** [comment]
Not reproducible on OS X.

**Comment by Arithmeticae** [comment]
![ctrl behavior](https://cloud.githubusercontent.com/assets/15927569/13504081/d60ca654-e140-11e5-985a-eaaa4ce4e611.gif)

In this gif, I demonstrate CTRL behavior on an item that has a single definition, LowPassFilter(), which behaves as expected, and two that have identically named functions in other classes, init() and update().

The behavior described occurs whether the function name is highlighted or not. The only requirement being that the mouse is hovering over the name.

I know it's not super apparent when I am pressing the CTRL key, but trust that I am and it is all I am pressing.

**Comment by csholmq** [comment]
I can reproduce. Agreed that is annoying. A workaround could be to introduce a delay.

**Comment by csholmq** [comment]
Difficult to sort out the behaviour here. 

- One match
  - Symbol not selected
    - Overlay should be instant
  - Symbol selected
    - Overlay should be instant
- Multiple matches
  - Symbol not selected
    - Quick pick should be instant
  - Symbol selected
    - What to do here?

**Comment by Arithmeticae** [comment]
My immediate thought is simply to remove any action for Ctrl+Hover.

Barring that, I would argue that when there are multiple matches, no action should be taken. Currently if there are multiple matches, the drop down displays, yet selecting something from that drop down list has no effect. 

If in the future, choices were remember on a class by class basis, then I could see value in selecting something from the drop down (quick pick?), but that with the same problem while not answer the question at hand.

**Comment by csholmq** [comment]
>Currently if there are multiple matches, the drop down displays, yet selecting something from that drop down list has no effect.

Fair enough. Though you still see which files are relevant.

**Comment by austin-----** [comment]
Thanks for the fix :)
