### ISSUE TITLE
Find All Reference doesn't work On Ubuntu

### ISSUE THREAD

**Issue by meilin996** [austin-----/code-gnu-global#39]
`$ uname -a`
`Linux linmei-Aspire-V5-573G 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
vscode have updated to newest.
As you can see, even though there is a function list_init just called on the line before it, it still show "no results".
![image](https://user-images.githubusercontent.com/11593073/39466327-ed603482-4d5a-11e8-9961-bb9ffe19cb37.png)

**Comment by carsonburr** [comment]
In the root of your project, run:
```
$ gtags
```

That really should be included in the setup instructions
