### ISSUE TITLE
no symbols found

### ISSUE THREAD

**Issue by ruurdboeke** [austin-----/code-gnu-global#6]
what is the best way to debug the issue? I have gtags in my path, ran gtags in a folder which created pretty big files, opened vscode and loaded that folder. No symbols are shown though.

**Comment by austin-----** [comment]
@ruurdboeke , two things to begin with:

1. what is the output of 'global --version'?

2. if you run 'global --encode-path " " -xa <symbol>', what does it show?

**Comment by ruurdboeke** [comment]
I sent you an email with the results of those, not sure if they will show up here. However, after opening vs code again, and _reinstalling_ the extension, it started working. I'm not sure why, but that is awesome, so we can close this issue. 

Do you expect the extension to pickup the changed gtags whenever I update them?

**Comment by austin-----** [comment]
Glad you got it working. Whenever the gtags got updated (after running gtags), the extension will pickup it.
