### ISSUE TITLE
Feature Request: Provide Function's Parameters

### ISSUE THREAD

**Issue by rei-vilo** [austin-----/code-gnu-global#7]
Below an example with Xcode.

<img width="463" alt="capture 2016-01-20 a 09 26 44" src="https://cloud.githubusercontent.com/assets/951776/12443433/133bfd78-bf58-11e5-97b2-4acb7d40cf35.png">

**Comment by austin-----** [comment]
Done. Please upgrade to 0.1.8 :)

**Comment by rei-vilo** [comment]
Thanks!
